# Generated by rust2rpm 13
# * No actix-http-test
%bcond_with check
%global debug_package %{nil}

%global crate actix-http

Name:           rust-%{crate}
Version:        1.0.1
Release:        2%{?dist}
Summary:        Actix http primitives

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/actix-http
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Actix http primitives.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGES.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+actix-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+actix-tls-devel %{_description}

This package contains library source intended for building other packages
which use "actix-tls" feature of "%{crate}" crate.

%files       -n %{name}+actix-tls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+brotli2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+brotli2-devel %{_description}

This package contains library source intended for building other packages
which use "brotli2" feature of "%{crate}" crate.

%files       -n %{name}+brotli2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+compress-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compress-devel %{_description}

This package contains library source intended for building other packages
which use "compress" feature of "%{crate}" crate.

%files       -n %{name}+compress-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+fail-ure-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fail-ure-devel %{_description}

This package contains library source intended for building other packages
which use "fail-ure" feature of "%{crate}" crate.

%files       -n %{name}+fail-ure-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+failure-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+failure-devel %{_description}

This package contains library source intended for building other packages
which use "failure" feature of "%{crate}" crate.

%files       -n %{name}+failure-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+flate2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+flate2-devel %{_description}

This package contains library source intended for building other packages
which use "flate2" feature of "%{crate}" crate.

%files       -n %{name}+flate2-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-devel %{_description}

This package contains library source intended for building other packages
which use "openssl" feature of "%{crate}" crate.

%files       -n %{name}+openssl-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+ring-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ring-devel %{_description}

This package contains library source intended for building other packages
which use "ring" feature of "%{crate}" crate.

%files       -n %{name}+ring-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-devel %{_description}

This package contains library source intended for building other packages
which use "rustls" feature of "%{crate}" crate.

%files       -n %{name}+rustls-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+secure-cookies-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+secure-cookies-devel %{_description}

This package contains library source intended for building other packages
which use "secure-cookies" feature of "%{crate}" crate.

%files       -n %{name}+secure-cookies-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Dec 20 18:39:39 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.1-2
- Regenerate

* Fri Dec 20 11:18:28 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.1-1
- Update to 1.0.1

* Fri Dec 13 19:45:14 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.0-1
- Update to 0.2.10

* Sun Aug 25 08:30:11 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.9-1
- Update to 0.2.9

* Sat Aug 03 13:48:15 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.8-1
- Update to 0.2.8

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.5-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Jun 30 11:56:04 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.5-1
- Update to 0.2.5

* Tue Jun 18 08:40:33 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.4-1
- Update to 0.2.4

* Sun Jun 02 10:42:32 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.3-1
- Update to 0.2.3

* Fri May 31 19:12:46 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.2-1
- Initial package
